"""Report generation service for PDF and Excel exports."""
import io
from typing import Dict
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill


class ReportGenerator:
    def generate_impact_pdf(self, impact_data: Dict) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4)
        styles = getSampleStyleSheet()
        elements = []
        elements.append(Paragraph("InvestIQ Africa - Investment Impact Report", styles["Title"]))
        elements.append(Spacer(1, 20))
        elements.append(Paragraph("ZIDA Investment Intelligence Platform", styles["Normal"]))
        elements.append(Spacer(1, 30))

        if "job_creation" in impact_data:
            elements.append(Paragraph("Job Creation Impact", styles["Heading2"]))
            jc = impact_data["job_creation"]
            data = [["Metric", "Value"],
                    ["Direct Jobs", str(jc.get("direct_jobs", 0))],
                    ["Indirect Jobs", str(jc.get("indirect_jobs", 0))],
                    ["Induced Jobs", str(jc.get("induced_jobs", 0))],
                    ["Total Jobs", str(jc.get("total_jobs", 0))]]
            table = Table(data, colWidths=[200, 200])
            table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#009739")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ]))
            elements.append(table)
            elements.append(Spacer(1, 20))

        if "gdp_contribution" in impact_data:
            elements.append(Paragraph("GDP Contribution", styles["Heading2"]))
            gdp = impact_data["gdp_contribution"]
            data = [["Metric", "Value (USD)"],
                    ["Direct GDP", f"${gdp.get('direct_gdp', 0):,.0f}"],
                    ["Multiplier Effect", f"${gdp.get('multiplier_effect', 0):,.0f}"],
                    ["Total GDP Impact", f"${gdp.get('total_gdp', 0):,.0f}"]]
            table = Table(data, colWidths=[200, 200])
            table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#009739")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 1, colors.grey),
            ]))
            elements.append(table)

        elements.append(Spacer(1, 30))
        elements.append(Paragraph("Generated by InvestIQ Africa | 7Square Inc.", styles["Normal"]))
        doc.build(elements)
        return buffer.getvalue()

    def generate_impact_excel(self, impact_data: Dict) -> bytes:
        wb = Workbook()
        ws = wb.active
        ws.title = "Impact Report"
        header_fill = PatternFill(start_color="009739", end_color="009739", fill_type="solid")
        header_font = Font(color="FFFFFF", bold=True)
        ws.append(["InvestIQ Africa - Investment Impact Report"])
        ws.merge_cells("A1:D1")
        ws["A1"].font = Font(size=16, bold=True)
        ws.append([])

        if "job_creation" in impact_data:
            jc = impact_data["job_creation"]
            ws.append(["Job Creation Impact"])
            ws.append(["Metric", "Value"])
            for cell in ws[ws.max_row]:
                cell.fill = header_fill
                cell.font = header_font
            ws.append(["Direct Jobs", jc.get("direct_jobs", 0)])
            ws.append(["Indirect Jobs", jc.get("indirect_jobs", 0)])
            ws.append(["Induced Jobs", jc.get("induced_jobs", 0)])
            ws.append(["Total Jobs", jc.get("total_jobs", 0)])
            ws.append([])

        if "roi_timeline" in impact_data:
            roi = impact_data["roi_timeline"]
            ws.append(["ROI Timeline"])
            ws.append(["Year", "Revenue", "Operating Cost", "Cash Flow", "Cumulative"])
            for cell in ws[ws.max_row]:
                cell.fill = header_fill
                cell.font = header_font
            for i, y in enumerate(roi.get("years", [])):
                ws.append([y, roi["revenue"][i], roi["opex"][i], roi["cash_flow"][i], roi["cumulative_cash_flow"][i]])

        ws.column_dimensions["A"].width = 25
        ws.column_dimensions["B"].width = 20
        ws.column_dimensions["C"].width = 20
        ws.column_dimensions["D"].width = 20
        ws.column_dimensions["E"].width = 20
        buffer = io.BytesIO()
        wb.save(buffer)
        return buffer.getvalue()
