"""Zimbabwe Special Economic Zones reference data."""

SEZ_DATA = [
    {
        "name": "Sunway City SEZ",
        "location_province": "Harare",
        "total_area_hectares": 498.0,
        "occupied_percentage": 35.0,
        "target_sectors": ["MAN", "ICT", "FIN"],
        "total_investment_attracted": 320_000_000,
        "total_jobs_created": 4200,
        "incentive_package": {
            "corporate_tax_rate": 0.0,
            "tax_holiday_years": 5,
            "post_holiday_tax_rate": 0.15,
            "standard_tax_rate": 0.2575,
            "duty_free_imports": True,
            "duty_free_raw_materials": True,
            "duty_free_capital_goods": True,
            "profit_repatriation": True,
            "reduced_licensing": True,
            "special_immigration": True,
        },
    },
    {
        "name": "Beitbridge SEZ",
        "location_province": "Matabeleland South",
        "total_area_hectares": 200.0,
        "occupied_percentage": 15.0,
        "target_sectors": ["MAN", "INF", "AGR"],
        "total_investment_attracted": 85_000_000,
        "total_jobs_created": 1100,
        "incentive_package": {
            "corporate_tax_rate": 0.0,
            "tax_holiday_years": 5,
            "post_holiday_tax_rate": 0.15,
            "standard_tax_rate": 0.2575,
            "duty_free_imports": True,
            "duty_free_raw_materials": True,
            "duty_free_capital_goods": True,
            "profit_repatriation": True,
            "reduced_licensing": True,
            "border_proximity_advantage": True,
        },
    },
    {
        "name": "Feruka-Mutare SEZ",
        "location_province": "Manicaland",
        "total_area_hectares": 310.0,
        "occupied_percentage": 20.0,
        "target_sectors": ["ENR", "MAN", "AGR"],
        "total_investment_attracted": 145_000_000,
        "total_jobs_created": 1800,
        "incentive_package": {
            "corporate_tax_rate": 0.15,
            "tax_holiday_years": 3,
            "post_holiday_tax_rate": 0.15,
            "standard_tax_rate": 0.2575,
            "duty_free_imports": True,
            "duty_free_raw_materials": True,
            "duty_free_capital_goods": True,
            "profit_repatriation": True,
            "pipeline_access": True,
        },
    },
    {
        "name": "Victoria Falls SEZ",
        "location_province": "Matabeleland North",
        "total_area_hectares": 150.0,
        "occupied_percentage": 45.0,
        "target_sectors": ["TOU", "ICT", "FIN"],
        "total_investment_attracted": 210_000_000,
        "total_jobs_created": 3500,
        "incentive_package": {
            "corporate_tax_rate": 0.0,
            "tax_holiday_years": 5,
            "post_holiday_tax_rate": 0.15,
            "standard_tax_rate": 0.2575,
            "duty_free_imports": True,
            "duty_free_raw_materials": True,
            "profit_repatriation": True,
            "tourism_incentives": True,
            "reduced_licensing": True,
        },
    },
    {
        "name": "Bulawayo SEZ",
        "location_province": "Bulawayo",
        "total_area_hectares": 250.0,
        "occupied_percentage": 25.0,
        "target_sectors": ["MAN", "MIN", "INF"],
        "total_investment_attracted": 120_000_000,
        "total_jobs_created": 2100,
        "incentive_package": {
            "corporate_tax_rate": 0.0,
            "tax_holiday_years": 5,
            "post_holiday_tax_rate": 0.15,
            "standard_tax_rate": 0.2575,
            "duty_free_imports": True,
            "duty_free_raw_materials": True,
            "duty_free_capital_goods": True,
            "profit_repatriation": True,
            "industrial_park_access": True,
        },
    },
]
