"""Zimbabwe investment sectors aligned with ZIDA priority areas."""

SECTORS_DATA = [
    {
        "name": "Mining & Quarrying",
        "code": "MIN",
        "description": "Gold, platinum, lithium, chrome, diamonds, and other mineral extraction. Zimbabwe holds the world's second-largest platinum and chrome reserves, and significant lithium deposits critical for EV batteries.",
        "avg_return_rate": 0.18,
        "risk_score": 65.0,
        "growth_rate_5yr": 0.082,
        "contribution_to_gdp": 0.125,
        "employment_multiplier": 4.2,
        "priority_sector": True,
    },
    {
        "name": "Agriculture & Agro-processing",
        "code": "AGR",
        "description": "Tobacco, horticulture, livestock, cotton, and food processing. Zimbabwe is one of the largest tobacco producers globally, with significant potential in macadamia, avocado, and blueberry exports.",
        "avg_return_rate": 0.14,
        "risk_score": 55.0,
        "growth_rate_5yr": 0.058,
        "contribution_to_gdp": 0.172,
        "employment_multiplier": 8.5,
        "priority_sector": True,
    },
    {
        "name": "Tourism & Hospitality",
        "code": "TOU",
        "description": "Victoria Falls (UNESCO World Heritage), safari tourism, cultural tourism, eco-tourism, and MICE. Zimbabwe offers world-class wildlife and natural attractions.",
        "avg_return_rate": 0.16,
        "risk_score": 50.0,
        "growth_rate_5yr": 0.125,
        "contribution_to_gdp": 0.068,
        "employment_multiplier": 7.2,
        "priority_sector": True,
    },
    {
        "name": "Manufacturing",
        "code": "MAN",
        "description": "Textiles, chemicals, food processing, beverages, and steel. Supported by industrial parks and SEZs with favourable incentives for value addition.",
        "avg_return_rate": 0.15,
        "risk_score": 58.0,
        "growth_rate_5yr": 0.042,
        "contribution_to_gdp": 0.113,
        "employment_multiplier": 5.8,
        "priority_sector": True,
    },
    {
        "name": "ICT & Digital Economy",
        "code": "ICT",
        "description": "Software development, fintech, telecoms infrastructure, data centres, and digital services. Fast-growing sector with a young, educated workforce.",
        "avg_return_rate": 0.22,
        "risk_score": 45.0,
        "growth_rate_5yr": 0.185,
        "contribution_to_gdp": 0.032,
        "employment_multiplier": 3.5,
        "priority_sector": True,
    },
    {
        "name": "Energy",
        "code": "ENR",
        "description": "Solar, hydro (Kariba expansion), thermal, and biomass energy generation. Zimbabwe targets 2,000 MW additional capacity from renewables by 2030.",
        "avg_return_rate": 0.13,
        "risk_score": 42.0,
        "growth_rate_5yr": 0.098,
        "contribution_to_gdp": 0.045,
        "employment_multiplier": 2.8,
        "priority_sector": True,
    },
    {
        "name": "Infrastructure & Construction",
        "code": "INF",
        "description": "Roads, bridges, housing, water and sanitation, and urban development. Major infrastructure deficit creates significant investment opportunities.",
        "avg_return_rate": 0.12,
        "risk_score": 48.0,
        "growth_rate_5yr": 0.075,
        "contribution_to_gdp": 0.082,
        "employment_multiplier": 6.5,
        "priority_sector": False,
    },
    {
        "name": "Financial Services",
        "code": "FIN",
        "description": "Banking, insurance, microfinance, mobile money, and capital markets. Growing sector with increasing digital adoption and financial inclusion initiatives.",
        "avg_return_rate": 0.20,
        "risk_score": 52.0,
        "growth_rate_5yr": 0.062,
        "contribution_to_gdp": 0.078,
        "employment_multiplier": 2.2,
        "priority_sector": False,
    },
    {
        "name": "Health & Pharmaceuticals",
        "code": "HLT",
        "description": "Pharmaceutical manufacturing, hospital development, medical tourism, and health tech. Significant import substitution opportunities for essential medicines.",
        "avg_return_rate": 0.17,
        "risk_score": 40.0,
        "growth_rate_5yr": 0.112,
        "contribution_to_gdp": 0.028,
        "employment_multiplier": 4.0,
        "priority_sector": True,
    },
]
